config/routes.rb
Fuga326::Application.routes.draw do
  get 'reception/index'
  get 'receptions/index'

  devise_for :users, controllers: {
        :registrations => 'users/registrations',
        :sessions => 'users/sessions',
        :passwords => 'users/passwords'
      }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  root :to => 'dashboard#index'
  
  get '/home'      => 'dashboard#index',  :as => :home

  get 'bs' ,to: 'bs#index'

  get 'bs_abs_content_bag/json_cat', to: 'bs_abs_content_bag#json_cat'

  get 'bs_config/company_show_shop', to: 'bs_config#company_show_shop'
  patch 'bs_config/company_update_shop', to: 'bs_config#company_update_shop'
  post 'bs_config/shop_create_staff', to: 'bs_config#shop_create_staff'
  patch 'bs_config/shop_update_staff', to: 'bs_config#shop_update_staff'
  delete 'bs_config/shop_delete_staff', to: 'bs_config#shop_delete_staff'
  post 'bs_config/shop_create_user', to: 'bs_config#shop_create_user'
  patch 'bs_config/shop_update_user', to: 'bs_config#shop_update_user'
  delete 'bs_config/shop_delete_user', to: 'bs_config#shop_delete_user'
  patch 'bs_config/shop_update_website', to: 'bs_config#shop_update_website'
  post 'bs_config/shop_create_fixed_link', to: 'bs_config#shop_create_fixed_link'
  post 'bs_config/shop_create_fixed_page', to: 'bs_config#shop_create_fixed_page'
  patch 'bs_config/navigation_update', to: 'bs_config#navigation_update'
  patch 'bs_config/update_fix_page', to: 'bs_config#update_fix_page'
  delete 'bs_config/shop_delete_fixed_link', to: 'bs_config#shop_delete_fixed_link'
  post 'bs_config/create_page_photo', to: 'bs_config#create_page_photo'
  delete 'bs_config/delete_page_photo', to: 'bs_config#delete_page_photo'

  post 'bs_config/create_shop_photo', to: 'bs_config#create_shop_photo'
  delete 'bs_config/delete_shop_photo', to: 'bs_config#delete_shop_photo'

  post 'bs_config/create_staff_photo', to:'bs_config#create_staff_photo'
  delete 'bs_config/delete_staff_photo', to:'bs_config#delete_staff_photo'

  post 'bs_config/shop_update_position', to: 'bs_config#shop_update_position'
  delete 'bs_config/shop_delete_position', to:'bs_config#shop_delete_position'

  get 'bs_authoring/index', to: 'bs_authoring#index'
  get 'bs_authoring/list_layout_schemes', to: 'bs_authoring#list_layout_schemes'
  get 'bs_authoring/list_color_schemes', to: 'bs_authoring#list_color_schemes'
  post 'bs_authoring/create_widget_bag_photo', to: 'bs_authoring#create_widget_bag_photo'
  delete 'bs_authoring/delete_widget_bag_photo', to: 'bs_authoring#delete_widget_bag_photo'
  post 'bs_authoring/update_widget_bag', to: 'bs_authoring#update_widget_bag'
  post 'bs_authoring/layout_for_edit', to: 'bs_authoring#layout_for_edit'
  post 'bs_authoring/layout_for_deploy', to: 'bs_authoring#layout_for_deploy'
  post 'bs_authoring/layout_for_nil', to: 'bs_authoring#layout_for_nil'
  post 'bs_authoring/color_for_deploy', to: 'bs_authoring#color_for_deploy'
  post 'bs_authoring/color_for_edit', to: 'bs_authoring#color_for_edit'
  post 'bs_authoring/color_for_nil', to: 'bs_authoring#color_for_nil'

  post 'dashboard/company_create', to: 'dashboard#company_create'
  patch 'dashboard/company_update', to: 'dashboard#company_update'
  delete 'dashboard/company_delete', to: 'dashboard#company_delete'
  post 'dashboard/company_create_shop', to: 'dashboard#company_create_shop'
  patch 'dashboard/company_update_shop', to: 'dashboard#company_update_shop'
  delete 'dashboard/company_delete_shop', to: 'dashboard#company_delete_shop'
  post 'dashboard/company_create_user', to: 'dashboard#company_create_user'
  patch 'dashboard/company_update_user', to: 'dashboard#company_update_user'
  delete 'dashboard/company_delete_user', to: 'dashboard#company_delete_user'
  post 'dashboard/shop_create_staff', to: 'dashboard#shop_create_staff'
  patch 'dashboard/shop_update_staff', to: 'dashboard#shop_update_staff'
  delete 'dashboard/shop_delete_staff', to: 'dashboard#shop_delete_staff'
  post 'dashboard/shop_create_user', to: 'dashboard#shop_create_user'
  patch 'dashboard/shop_update_user', to: 'dashboard#shop_update_user'
  patch 'dashboard/shop_update_user_ui', to: 'dashboard#shop_update_user_ui'
  delete 'dashboard/shop_delete_user', to: 'dashboard#shop_delete_user'
  post 'dashboard/shop_create_favicon', to: 'dashboard#shop_create_favicon'

  post 'dashboard/layout_create', to: 'dashboard#layout_create'
  patch 'dashboard/layout_update', to: 'dashboard#layout_update'
  delete 'dashboard/layout_delete', to: 'dashboard#layout_delete'
  post 'dashboard/create_layout_photo', to: 'dashboard#create_layout_photo'
  delete 'dashboard/delete_layout_photo', to: 'dashboard#delete_layout_photo'
  post 'dashboard/color_create', to: 'dashboard#color_create'
  patch 'dashboard/color_update', to: 'dashboard#color_update'
  delete 'dashboard/color_delete', to: 'dashboard#color_delete'
  post 'dashboard/create_color_photo', to: 'dashboard#create_color_photo'
  delete 'dashboard/delete_color_photo', to: 'dashboard#delete_color_photo'
  post 'dashboard/widget_create', to: 'dashboard#widget_create'
  patch 'dashboard/widget_update', to: 'dashboard#widget_update'
  delete 'dashboard/widget_delete', to: 'dashboard#widget_delete'

  patch 'dashboard/shop_update_website', to: 'dashboard#shop_update_website'
  delete 'dashboard/shop_reset_favicon', to: 'dashboard#shop_reset_favicon'
  post 'dashboard/shop_create_apple_touch_icon', to: 'dashboard#shop_create_apple_touch_icon'
  delete 'dashboard/shop_reset_apple_touch_icon', to: 'dashboard#shop_reset_apple_touch_icon'
  patch 'dashboard/set_disqus_mode', to: 'dashboard#set_disqus_mode'
  patch 'dashboard/set_disqus_code', to: 'dashboard#set_disqus_code'

  post 'dashboard/shop_update_position', to: 'dashboard#shop_update_position'
  delete 'dashboard/shop_delete_position', to: 'dashboard#shop_delete_position'
  post 'dashboard/delegating', to: 'dashboard#delegating'
  post 'dashboard/roll_back', to: 'dashboard#roll_back'
  post 'dashboard/user_create', to: 'dashboard#user_create'
  patch 'dashboard/user_update', to: 'dashboard#user_update'
  delete 'dashboard/user_delete', to: 'dashboard#user_delete'

  get 'bs_content_gallery/content_root', to: 'bs_content_gallery#content_root'
  patch 'bs_content_gallery/content_category', to: 'bs_content_gallery#content_category'
  post 'bs_content_gallery/create_bag', to: 'bs_content_gallery#create_bag'
  patch 'bs_content_gallery/update_bag', to: 'bs_content_gallery#update_bag'
  delete 'bs_content_gallery/delete_bag', to: 'bs_content_gallery#delete_bag'
  post 'bs_content_gallery/create_leaf', to: 'bs_content_gallery#create_leaf'
  patch 'bs_content_gallery/update_leaf', to: 'bs_content_gallery#update_leaf'
  delete 'bs_content_gallery/delete_leaf', to: 'bs_content_gallery#delete_leaf'
  post 'bs_content_gallery/create_face_photo', to: 'bs_content_gallery#create_face_photo'
  patch 'bs_content_gallery/update_face_photo', to: 'bs_content_gallery#update_face_photo'
  delete 'bs_content_gallery/delete_face_photo', to: 'bs_content_gallery#delete_face_photo'
  post 'bs_content_gallery/create_photo', to: 'bs_content_gallery#create_photo'
  patch 'bs_content_gallery/update_photo', to: 'bs_content_gallery#update_photo'
  delete 'bs_content_gallery/delete_photo', to: 'bs_content_gallery#delete_photo'
  post 'bs_content_gallery/content_category_create', to: 'bs_content_gallery#content_category_create'
  patch 'bs_content_gallery/content_category_update', to: 'bs_content_gallery#content_category_update'
  delete 'bs_content_gallery/content_category_delete', to: 'bs_content_gallery#content_category_delete'

  get 'admin_content_gallery/content_root', to: 'admin_content_gallery#content_root'
  patch 'admin_content_gallery/content_category', to: 'admin_content_gallery#content_category'
  post 'admin_content_gallery/create_bag', to: 'admin_content_gallery#create_bag'
  patch 'admin_content_gallery/update_bag', to: 'admin_content_gallery#update_bag'
  delete 'admin_content_gallery/delete_bag', to: 'admin_content_gallery#delete_bag'
  post 'admin_content_gallery/create_leaf', to: 'admin_content_gallery#create_leaf'
  patch 'admin_content_gallery/update_leaf', to: 'admin_content_gallery#update_leaf'
  delete 'admin_content_gallery/delete_leaf', to: 'admin_content_gallery#delete_leaf'
  post 'admin_content_gallery/create_face_photo', to: 'admin_content_gallery#create_face_photo'
  patch 'admin_content_gallery/update_face_photo', to: 'admin_content_gallery#update_face_photo'
  delete 'admin_content_gallery/delete_face_photo', to: 'admin_content_gallery#delete_face_photo'
  post 'admin_content_gallery/create_photo', to: 'admin_content_gallery#create_photo'
  patch 'admin_content_gallery/update_photo', to: 'admin_content_gallery#update_photo'
  delete 'admin_content_gallery/delete_photo', to: 'admin_content_gallery#delete_photo'
  post 'admin_content_gallery/content_category_create', to: 'admin_content_gallery#content_category_create'
  patch 'admin_content_gallery/content_category_update', to: 'admin_content_gallery#content_category_update'
  delete 'admin_content_gallery/content_category_delete', to: 'admin_content_gallery#content_category_delete'
  
  get 'bs_content_portfolio/content_root', to: 'bs_content_portfolio#content_root'
  patch 'bs_content_portfolio/content_category', to: 'bs_content_portfolio#content_category'
  post 'bs_content_portfolio/create_bag', to: 'bs_content_portfolio#create_bag'
  patch 'bs_content_portfolio/update_bag', to: 'bs_content_portfolio#update_bag'
  delete 'bs_content_portfolio/delete_bag', to: 'bs_content_portfolio#delete_bag'
  post 'bs_content_portfolio/create_leaf', to: 'bs_content_portfolio#create_leaf'
  patch 'bs_content_portfolio/update_leaf', to: 'bs_content_portfolio#update_leaf'
  delete 'bs_content_portfolio/delete_leaf', to: 'bs_content_portfolio#delete_leaf'

app/views/layouts/assets/yoshilabo/_footer.erb
<div id="gotop"><i class="fa fa-angle-up"></i></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/javascripts/assets/vendor/jquery-2.1.3.min"><\/script>')</script>
<%= javascript_include_tag "/javascripts/assets/yoshilabo/swifty.js" %>
<% unless @website.analytics_code.blank? %>
<%= raw @website.analytics_code %>
<% end %>

app/views/layouts/assets/yoshilabo/_header.erb
        <!-- このサイトはIE9未満では正しく表示されません。 -->
        <!--[if lt IE 9]>
        <p id="browserupgrade">あなたは<strong>古いブラウザ</strong>をご利用のようです。安心してインターネットをお楽しみいただくために<a href="http://windows.microsoft.com/ja-jp/internet-explorer/download-ie">最新のブラウザにアップグレード</a>してください。このサイトは古いブラウザでは正しく表示されません。</p>
        <![endif]-->
        <header id="header">
            <div class="container">
                <div id="header_main" >
                    <h1><a href="/home?wkey=<%= @website.wsite_hash_key %>"><%= @website.name %></a></h1>
                </div>
                <div id="header_side">
                    <%= raw("<a href=#{@website.social_facebook_uri} target='_blank' ><i class='fa fa-facebook-official'></i></a>") unless @website.social_facebook_uri.blank? %>
                    <div class="fb-like" data-href="http://www.yoshilabo.jp/home" data-width="80" data-layout="box_count" data-share="false"></div>
                    <div class="fb-share-button" data-href="http://www.yoshilabo.jp/home" data-layout="box_count" data-mobile-iframe="true" style="vertical-align:top;"></div>
                    <div class="g-plusone" data-size="tall"></div>
                    <a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja" data-count="vertical">ツイート</a>
                    <button id="smart_nav_opener_btn"><i class="fa fa-bars"></i><div>MENU</div></button>
                </div>
            </div>
        </header>

app/views/layouts/assets/yoshilabo/_item_news_bag.erb
<% latests = temp_local.public_leafs %>
<% unless latests.blank? %>
                                <li class="col-1p2">
    <% link_url = url_for(:action=>'news_list', :id=>temp_local, :wkey=>@website.wsite_hash_key) %>
    <% key_photo = key_photo(latests[0]) %>
    <% unless key_photo.blank? %>
                                    <div class="imgbox"><div style="background-image: url('<%= key_photo.clip.url(:panel) %>')">
                                        <a href="<%= link_url %>"><img src="<%= key_photo.clip.url(:panel) %>"></a>
    <% else %>
                                    <div class="imgbox"><div style="background-image: url('//placehold.it/400x400/ffffff/cccccc&amp;text=<%=temp_local.publish_from.strftime('%Y-%m-%d')%>')">
                                        <a href="<%= link_url %>"><img src="//placehold.it/400x400/ffffff/cccccc&amp;text=<%=temp_local.publish_from.strftime('%Y-%m-%d')%>"></a>
    <% end %>
                                    </div></div>
                                    <h1><a href="<%= link_url %>"><%= truncate(model_name(temp_local)) %></a></h1>
<% end %>

app/views/layouts/assets/yoshilabo/_item_news_list.erb
<% link_url = url_for(:action=>'news_show', :id=>@leaf, :page=>@page, :wkey=>@website.wsite_hash_key) %>
<% key_photo = key_photo(@leaf) %>
                            <li class="clearfix">
                                <div class="col-1p3">
<% unless key_photo.blank? %>
                                    <div class="imgbox"><div style="background-image: url('<%= key_photo.clip.url(:panel) %>')">
                                        <a href="<%= link_url %>">
                                            <img src="<%= key_photo.clip.url(:panel) %>">
                                        </a>
                                    </div></div>
<% else %>
                                    <div class="imgbox"><div style="background-image: url('//placehold.it/400x400/ffffff/cccccc&amp;text=<%=@leaf.publish_from.strftime('%Y-%m-%d')%>')">
                                        <a href="<%= link_url %>">
                                            <img src="//placehold.it/400x400/ffffff/cccccc&amp;text=<%=@leaf.publish_from.strftime('%Y-%m-%d')%>">
                                        </a>
                                    </div></div>
<% end %>
                                </div>
                                <div class="col-2p3">
                                    <h2><a href="<%= link_url %>"><%= h model_title(@leaf) %></a></h2>
                                    <div class="cat">
                                        <i class="fa fa-calendar"></i> <%= publish_label(@leaf) %>
                                    </div>
                                    <p><%= h  truncate(strip_tags(@leaf.description).gsub('&nbsp;', ' '), :length=>200) unless @leaf.description.blank?%></p>
                                </div>
                            </li>

app/views/layouts/assets/yoshilabo/_latest_news.erb
<%
    @max = 12
    type_root = ContentCategory.type_root(@website, ContentCategory::TYPE_NEWS)
    navigation = type_root.web_page
    bag_categories = type_root.children.where('is_public=?', true)

    public_categories  = []
    bag_categories.each do | cat |
        public_categories.concat(cat.sons)
        public_categories << cat
    end
    latest_leafs = @website.public_leafs.where("content_category_id IN (?)", public_categories).order(publish_from: :desc).order(created_at: :desc).limit(@max)
    #c = ContentLeaf.public_leafs_condition
    #c.and "content_category_id", public_categories
    #latest_leafs =  @website.content_leafs.find(:all, :limit=>@max, :conditions=>c.where, :order=>'publish_from desc')
%>
<% unless latest_leafs.blank? %>
    <% latest_leafs.each do | leaf |  %>
                               <li class="clearfix">
                                    <div class="col-1p3 news_img">
        <% link_url  = url_for(:action=>'news_show', :id=>leaf, :wkey=>@website.wsite_hash_key) %>
        <% key_photo = key_photo(leaf) %>
        <% unless key_photo.blank? %>
            <% photo_url = key_photo.clip.url(:panel) %>
                                        <div class="imgbox"><div style="background-image: url('<%= photo_url %>')">
                                            <a href="<%= link_url %>"><img src="<%= photo_url %>"></a>
        <% else %>
    <% photo_url = '//placehold.it/240x240/ffffff/cccccc&amp;text='+leaf.publish_from.strftime('%Y-%m-%d') %>
                                        <div class="imgbox"><div style="background-image: url('<%= photo_url %>')">
                                            <a href="<%= link_url %>"><img src="<%= photo_url %>"></a>
        <% end %>
                                        </div></div>
                                        <div class="news_category cat_id<%= leaf.content_category_id %>">
                                            <%= model_name(leaf.content_category) %>
                                        </div>
                                    </div>
                                    <div class="col-2p3">
                                        <h1><a href="<%= link_url %>"><%= model_title(leaf) %></a></h1>
                                        <div class="cat"><%= model_name(leaf.content_category) %> <i class="fa fa-calendar"></i> <%= leaf.publish_from.strftime("%Y-%m-%d") %></div>
                                        <p><%= h truncate(strip_tags(leaf.description).gsub('&nbsp;', ' '), :length=>200) unless leaf.description.blank?%></p>
                                    </div>
                                </li>
   <% end %>
<% end %>

app/views/layouts/assets/yoshilabo/_navigation.erb
<%
    type_root = ContentCategory.type_root(@website, ContentCategory::TYPE_NEWS)
    news_bags =  type_root.public_bags
    unless news_bags.blank?
        news_bags.each do | leaf |
%>
        <li><a href="<%= url_for(:action=>'news_list', :id=>leaf, :wkey=>@website.wsite_hash_key) %>"><%= leaf.name %></a></li>
<%      end %>
<%  end %>
    <li>
        <% if @website.enable_inquiry %>
            <%= link_to "お問い合わせ".html_safe, inquiry_new_path %>
        <% end %>
    </li>
<% if @author_mode %>
        <li>
            <i class="fa fa-cog"></i> 設定
            <ul>
<!--
                <li><a href="<%= url_for(:action=>'list_color_schemes')%>">カラー</a></li>
-->
                <% unless @website.wsite_layout_deploy.is_public.blank? %>
                    <li><a href="<%= url_for(:action=>'list_layout_schemes')%>">デザイン</a></li>
                <% end %>
                <li><a href="<%= url_for(:action=>'manage_widget')%>">表示設定</a></li>
                <% if current_user.is_fuga_3? %>
                    <li><a href="<%= url_for(:controller=>'bs_config', :action=>'shop_show_website')%>"><i class="icon-off"></i>&nbsp;サイト編集終了</a></li>
                <% else %>
                    <li><a href="<%= url_for(:controller=>'admin_config', :action=>'shop_show_website')%>"><i class="icon-off"></i>&nbsp;サイト編集終了</a></li>
                <% end %>
            </ul>
        </li>
<% end %>

app/views/layouts/assets/yoshilabo/news_show.html.erb
<!doctype html>
<html lang="ja">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><%= model_title(@seed) %> - <%= @website.name %></title>
<meta name="viewport" content="initial-scale=1">
<% if request.host.include?('swifty.jp') || request.host.include?('956.jp') %>
    <meta name="robots"                   content="noindex,nofollow">
<% end %>
<meta name="format-detection" content="telephone=no">
<meta name="format-detection" content="address=no">
<meta name="application-name" content="swifty2">
<meta name="Targeted Geographic Area" content="Japan">
<meta name="generator" content="fuga">
<meta name="author" content="<%= model_name(@website.company) %>">
<meta property="og:type"   content="article">
<% if false %>
    <meta property="og:url"    content="https://<%= request.host %>/news_show?id=<%= @seed.id %>&wkey=<%= @website.wsite_hash_key %>">
<% end %>
<meta property="og:title"  content="<%= model_title(@seed) %> - <%= @website.name %>">
<meta property="og:site_name"   content="<%= @website.name %>">
<meta property="article:publisher" content="<%= model_name(@website.company) %>">
<% unless @website.custom_metas.blank? %>
    <%= raw @website.custom_metas %>
<% end %>
<%= auto_discovery_link_tag :rss, "/news_feed.rss", :title => @website.name %>
<%
    @favicon = @website.favicon
    @webclip = @website.apple_touch_icon
%>
<% unless @favicon.blank? %>
<link href="<%= @favicon.clip.url() %>" rel="icon" type="image/vnd.microsoft.icon"/>
<link href="<%= @favicon.clip.url() %>" rel="shortcut icon" type="image/x-icon"/>
<% end %>
<% unless @webclip.blank? %>
<link rel="apple-touch-icon" href="<%= @webclip.clip.url() %>">
<% end %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="/stylesheets/assets/yoshilabo/swifty.css">
<!-- <%= @seed.id %> -->
</head>
<!-- このサイトはIE9未満では正しく表示されません。 -->
<!--[if lt IE 9]>
<body id="ie8">
<![endif]-->
<!--[if IE 9]>
<body id="ie9">
<![endif]-->
<!--[if (gt IE 10)|!(IE)]><!-->
<body>
<!--<![endif]-->
<div id="fb-root"></div>
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<aside id="smart_nav">
    <ul id="smart_nav_inner">
        <li><%= @website.name %> - MENU</li>
        <li><a href="/home?wkey=<%= @website.wsite_hash_key %>">Home</a></li>
<%= render :partial=>"#{LayoutScheme.asset_root}/yoshilabo/navigation" %>
<% if request.host == 'yoshilabo.jp' || request.host == 'www.yoshilabo.jp' %>
        <li><a href="http://www.chgroup.jp/" target="_blank">Yoshiつねgroup SITE</a></li>
<% end %>
    </ul>
</aside>
<div id="body">
    <div id="body_inner">
<%= render :partial=>"#{LayoutScheme.asset_root}/yoshilabo/header" %>
        <div id="news">
            <div class="container">
                <div id="wrapper" class="wrapper">
                    <main id="main">
                        <article id="article" class="container">
                            <header>
                                <h1><%= h model_title(@seed) %></h1>
                                <p><%= model_name(@seed.content_category) %> <i class="fa fa-calendar"></i> <%= publish_label(@seed) %></p>
                            </header>
                            <div class="content">
<% unless @seed.description.blank? %><%= raw @seed.description %><% end %>
                    <% tag_cloud(@seed.tags.order(name: :asc), %w(css1 css2 css3 css4)) do |tag| %>
                        <% @seed.content_category.category_path(true).each do | category | %>
                        <% cat_url = url_for(:action=>'news_list', :id=>category, search_tags: [tag.name])%>
                            <a href='<%= cat_url %>'>
                                <span class='badge badge-primary '>
                                    #<%= tag3_icon %>&nbsp;<%= tag_name(tag) %>
                                </span>
                            </a>
                        <% end %>
                    <% end %>
                            </div>
                            <aside class="sns_buttons">
                                <div class="fb-like" data-width="80" data-layout="box_count" data-share="false"></div>
                                <div class="fb-share-button" data-layout="box_count" data-mobile-iframe="true"></div>
                                <div class="g-plusone" data-size="tall"></div>
                                <div style="display:inline-block;vertical-align: top;">
                                    <script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140411" ></script>
                                    <script type="text/javascript">
                                        new media_line_me.LineButton({"pc":true,"lang":"ja","type":"e"});
                                    </script>
                                </div>
                                <a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja" data-count="vertical">ツイート</a>
                            </aside>
                        </article>
                        <%= leaf_navigation(@seed) %>
                    </main>
                    <div id="sidebar">
                        <nav id="nav">
                            <ul>
                                <li><%= @website.name %> - MENU</li>
                                <li><a href="/home?wkey=<%= @website.wsite_hash_key %>">Home</a></li>
<%= render :partial=>"#{LayoutScheme.asset_root}/yoshilabo/navigation" %>
<% if request.host == 'yoshilabo.jp' || request.host == 'www.yoshilabo.jp' %>
                                <li><a href="http://www.chgroup.jp/" target="_blank">Yoshiつねgroup SITE</a></li>
<% end %>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <footer id="footer">
            <div class="container">
                <small><%= copyright_notice(@website) %></small>
            </div>
        </footer>
    </div>
</div>
<%= render :partial=>"#{LayoutScheme.asset_root}/yoshilabo/footer"%>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<script src="https://apis.google.com/js/platform.js" async defer>{lang: 'ja'}</script>
</body>
</html>